/*
 * This file is generated by jOOQ.
 */
package trash.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import trash.tables.Admin;


/**
 * 관리자 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdminRecord extends UpdatableRecordImpl<AdminRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trash.ADMIN.ADM_ID</code>. ID
     */
    public AdminRecord setAdmId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>trash.ADMIN.ADM_ID</code>. ID
     */
    public String getAdmId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>trash.ADMIN.ADM_PWD</code>. 비밀번호
     */
    public AdminRecord setAdmPwd(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>trash.ADMIN.ADM_PWD</code>. 비밀번호
     */
    public String getAdmPwd() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdminRecord
     */
    public AdminRecord() {
        super(Admin.ADMIN);
    }

    /**
     * Create a detached, initialised AdminRecord
     */
    public AdminRecord(String admId, String admPwd) {
        super(Admin.ADMIN);

        setAdmId(admId);
        setAdmPwd(admPwd);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AdminRecord
     */
    public AdminRecord(trash.tables.pojos.Admin value) {
        super(Admin.ADMIN);

        if (value != null) {
            setAdmId(value.getAdmId());
            setAdmPwd(value.getAdmPwd());
            resetChangedOnNotNull();
        }
    }
}
