/*
 * This file is generated by jOOQ.
 */
package trash.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import trash.tables.Notice;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NoticeRecord extends UpdatableRecordImpl<NoticeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>spotfinder.NOTICE.NTC_SEQ</code>. 공지 일련번호
     */
    public NoticeRecord setNtcSeq(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>spotfinder.NOTICE.NTC_SEQ</code>. 공지 일련번호
     */
    public ULong getNtcSeq() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>spotfinder.NOTICE.NTC_TTL</code>. 공지 제목
     */
    public NoticeRecord setNtcTtl(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>spotfinder.NOTICE.NTC_TTL</code>. 공지 제목
     */
    public String getNtcTtl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>spotfinder.NOTICE.NTC_CTT</code>. 공지 내용
     */
    public NoticeRecord setNtcCtt(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>spotfinder.NOTICE.NTC_CTT</code>. 공지 내용
     */
    public String getNtcCtt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spotfinder.NOTICE.NTC_VLD_YN</code>. 유효여부
     */
    public NoticeRecord setNtcVldYn(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>spotfinder.NOTICE.NTC_VLD_YN</code>. 유효여부
     */
    public String getNtcVldYn() {
        return (String) get(3);
    }

    /**
     * Setter for <code>spotfinder.NOTICE.CRE_DTM</code>. 등록일시
     */
    public NoticeRecord setCreDtm(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>spotfinder.NOTICE.CRE_DTM</code>. 등록일시
     */
    public LocalDateTime getCreDtm() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>spotfinder.NOTICE.UPD_DTM</code>. 수정일시
     */
    public NoticeRecord setUpdDtm(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>spotfinder.NOTICE.UPD_DTM</code>. 수정일시
     */
    public LocalDateTime getUpdDtm() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NoticeRecord
     */
    public NoticeRecord() {
        super(Notice.NOTICE);
    }

    /**
     * Create a detached, initialised NoticeRecord
     */
    public NoticeRecord(ULong ntcSeq, String ntcTtl, String ntcCtt, String ntcVldYn, LocalDateTime creDtm, LocalDateTime updDtm) {
        super(Notice.NOTICE);

        setNtcSeq(ntcSeq);
        setNtcTtl(ntcTtl);
        setNtcCtt(ntcCtt);
        setNtcVldYn(ntcVldYn);
        setCreDtm(creDtm);
        setUpdDtm(updDtm);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised NoticeRecord
     */
    public NoticeRecord(trash.tables.pojos.Notice value) {
        super(Notice.NOTICE);

        if (value != null) {
            setNtcSeq(value.getNtcSeq());
            setNtcTtl(value.getNtcTtl());
            setNtcCtt(value.getNtcCtt());
            setNtcVldYn(value.getNtcVldYn());
            setCreDtm(value.getCreDtm());
            setUpdDtm(value.getUpdDtm());
            resetChangedOnNotNull();
        }
    }
}
