/*
 * This file is generated by jOOQ.
 */
package trash.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.types.ULong;


/**
 * 시설물 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Facility implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong fcltySeq;
    private final String fcltyNm;
    private final String fcltyTyp;
    private final String fcltyLctn;
    private final String fcltyDtlLctn;
    private final BigDecimal fcltyLttd;
    private final BigDecimal fcltyLngt;
    private final String fcltyInfo;
    private final String fcltyDprNm;
    private final String fcltyDprTlphNmbr;
    private final String fcltyAprvYn;
    private final ULong mbrSeq;
    private final LocalDateTime creDtm;
    private final LocalDateTime updDtm;

    public Facility(Facility value) {
        this.fcltySeq = value.fcltySeq;
        this.fcltyNm = value.fcltyNm;
        this.fcltyTyp = value.fcltyTyp;
        this.fcltyLctn = value.fcltyLctn;
        this.fcltyDtlLctn = value.fcltyDtlLctn;
        this.fcltyLttd = value.fcltyLttd;
        this.fcltyLngt = value.fcltyLngt;
        this.fcltyInfo = value.fcltyInfo;
        this.fcltyDprNm = value.fcltyDprNm;
        this.fcltyDprTlphNmbr = value.fcltyDprTlphNmbr;
        this.fcltyAprvYn = value.fcltyAprvYn;
        this.mbrSeq = value.mbrSeq;
        this.creDtm = value.creDtm;
        this.updDtm = value.updDtm;
    }

    public Facility(
        ULong fcltySeq,
        String fcltyNm,
        String fcltyTyp,
        String fcltyLctn,
        String fcltyDtlLctn,
        BigDecimal fcltyLttd,
        BigDecimal fcltyLngt,
        String fcltyInfo,
        String fcltyDprNm,
        String fcltyDprTlphNmbr,
        String fcltyAprvYn,
        ULong mbrSeq,
        LocalDateTime creDtm,
        LocalDateTime updDtm
    ) {
        this.fcltySeq = fcltySeq;
        this.fcltyNm = fcltyNm;
        this.fcltyTyp = fcltyTyp;
        this.fcltyLctn = fcltyLctn;
        this.fcltyDtlLctn = fcltyDtlLctn;
        this.fcltyLttd = fcltyLttd;
        this.fcltyLngt = fcltyLngt;
        this.fcltyInfo = fcltyInfo;
        this.fcltyDprNm = fcltyDprNm;
        this.fcltyDprTlphNmbr = fcltyDprTlphNmbr;
        this.fcltyAprvYn = fcltyAprvYn;
        this.mbrSeq = mbrSeq;
        this.creDtm = creDtm;
        this.updDtm = updDtm;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.FCLTY_SEQ</code>. 시설물 일련번호
     */
    public ULong getFcltySeq() {
        return this.fcltySeq;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.FCLTY_NM</code>. 시설물명
     */
    public String getFcltyNm() {
        return this.fcltyNm;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.FCLTY_TYP</code>. 시설물 종류
     */
    public String getFcltyTyp() {
        return this.fcltyTyp;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.FCLTY_LCTN</code>. 위치
     */
    public String getFcltyLctn() {
        return this.fcltyLctn;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.FCLTY_DTL_LCTN</code>. 상세 위치
     */
    public String getFcltyDtlLctn() {
        return this.fcltyDtlLctn;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.FCLTY_LTTD</code>. 위도
     */
    public BigDecimal getFcltyLttd() {
        return this.fcltyLttd;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.FCLTY_LNGT</code>. 경도
     */
    public BigDecimal getFcltyLngt() {
        return this.fcltyLngt;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.FCLTY_INFO</code>. 정보
     */
    public String getFcltyInfo() {
        return this.fcltyInfo;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.FCLTY_DPR_NM</code>. 관리 부서명
     */
    public String getFcltyDprNm() {
        return this.fcltyDprNm;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.FCLTY_DPR_TLPH_NMBR</code>. 관리 부서
     * 전화번호
     */
    public String getFcltyDprTlphNmbr() {
        return this.fcltyDprTlphNmbr;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.FCLTY_APRV_YN</code>. 승인여부
     */
    public String getFcltyAprvYn() {
        return this.fcltyAprvYn;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.MBR_SEQ</code>. 회원 일련번호
     */
    public ULong getMbrSeq() {
        return this.mbrSeq;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.CRE_DTM</code>. 등록일시
     */
    public LocalDateTime getCreDtm() {
        return this.creDtm;
    }

    /**
     * Getter for <code>spotfinder.FACILITY.UPD_DTM</code>. 수정일시
     */
    public LocalDateTime getUpdDtm() {
        return this.updDtm;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Facility other = (Facility) obj;
        if (this.fcltySeq == null) {
            if (other.fcltySeq != null)
                return false;
        }
        else if (!this.fcltySeq.equals(other.fcltySeq))
            return false;
        if (this.fcltyNm == null) {
            if (other.fcltyNm != null)
                return false;
        }
        else if (!this.fcltyNm.equals(other.fcltyNm))
            return false;
        if (this.fcltyTyp == null) {
            if (other.fcltyTyp != null)
                return false;
        }
        else if (!this.fcltyTyp.equals(other.fcltyTyp))
            return false;
        if (this.fcltyLctn == null) {
            if (other.fcltyLctn != null)
                return false;
        }
        else if (!this.fcltyLctn.equals(other.fcltyLctn))
            return false;
        if (this.fcltyDtlLctn == null) {
            if (other.fcltyDtlLctn != null)
                return false;
        }
        else if (!this.fcltyDtlLctn.equals(other.fcltyDtlLctn))
            return false;
        if (this.fcltyLttd == null) {
            if (other.fcltyLttd != null)
                return false;
        }
        else if (!this.fcltyLttd.equals(other.fcltyLttd))
            return false;
        if (this.fcltyLngt == null) {
            if (other.fcltyLngt != null)
                return false;
        }
        else if (!this.fcltyLngt.equals(other.fcltyLngt))
            return false;
        if (this.fcltyInfo == null) {
            if (other.fcltyInfo != null)
                return false;
        }
        else if (!this.fcltyInfo.equals(other.fcltyInfo))
            return false;
        if (this.fcltyDprNm == null) {
            if (other.fcltyDprNm != null)
                return false;
        }
        else if (!this.fcltyDprNm.equals(other.fcltyDprNm))
            return false;
        if (this.fcltyDprTlphNmbr == null) {
            if (other.fcltyDprTlphNmbr != null)
                return false;
        }
        else if (!this.fcltyDprTlphNmbr.equals(other.fcltyDprTlphNmbr))
            return false;
        if (this.fcltyAprvYn == null) {
            if (other.fcltyAprvYn != null)
                return false;
        }
        else if (!this.fcltyAprvYn.equals(other.fcltyAprvYn))
            return false;
        if (this.mbrSeq == null) {
            if (other.mbrSeq != null)
                return false;
        }
        else if (!this.mbrSeq.equals(other.mbrSeq))
            return false;
        if (this.creDtm == null) {
            if (other.creDtm != null)
                return false;
        }
        else if (!this.creDtm.equals(other.creDtm))
            return false;
        if (this.updDtm == null) {
            if (other.updDtm != null)
                return false;
        }
        else if (!this.updDtm.equals(other.updDtm))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.fcltySeq == null) ? 0 : this.fcltySeq.hashCode());
        result = prime * result + ((this.fcltyNm == null) ? 0 : this.fcltyNm.hashCode());
        result = prime * result + ((this.fcltyTyp == null) ? 0 : this.fcltyTyp.hashCode());
        result = prime * result + ((this.fcltyLctn == null) ? 0 : this.fcltyLctn.hashCode());
        result = prime * result + ((this.fcltyDtlLctn == null) ? 0 : this.fcltyDtlLctn.hashCode());
        result = prime * result + ((this.fcltyLttd == null) ? 0 : this.fcltyLttd.hashCode());
        result = prime * result + ((this.fcltyLngt == null) ? 0 : this.fcltyLngt.hashCode());
        result = prime * result + ((this.fcltyInfo == null) ? 0 : this.fcltyInfo.hashCode());
        result = prime * result + ((this.fcltyDprNm == null) ? 0 : this.fcltyDprNm.hashCode());
        result = prime * result + ((this.fcltyDprTlphNmbr == null) ? 0 : this.fcltyDprTlphNmbr.hashCode());
        result = prime * result + ((this.fcltyAprvYn == null) ? 0 : this.fcltyAprvYn.hashCode());
        result = prime * result + ((this.mbrSeq == null) ? 0 : this.mbrSeq.hashCode());
        result = prime * result + ((this.creDtm == null) ? 0 : this.creDtm.hashCode());
        result = prime * result + ((this.updDtm == null) ? 0 : this.updDtm.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Facility (");

        sb.append(fcltySeq);
        sb.append(", ").append(fcltyNm);
        sb.append(", ").append(fcltyTyp);
        sb.append(", ").append(fcltyLctn);
        sb.append(", ").append(fcltyDtlLctn);
        sb.append(", ").append(fcltyLttd);
        sb.append(", ").append(fcltyLngt);
        sb.append(", ").append(fcltyInfo);
        sb.append(", ").append(fcltyDprNm);
        sb.append(", ").append(fcltyDprTlphNmbr);
        sb.append(", ").append(fcltyAprvYn);
        sb.append(", ").append(mbrSeq);
        sb.append(", ").append(creDtm);
        sb.append(", ").append(updDtm);

        sb.append(")");
        return sb.toString();
    }
}
