/*
 * This file is generated by jOOQ.
 */
package trash.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Member implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong mbrId;
    private final String mbrEmail;
    private final String mbrNckNm;
    private final String mbrGndr;
    private final String mbrSclId;
    private final String mbrSclTyp;
    private final String mbrArgmYn;
    private final String mbrVldYn;
    private final LocalDateTime creDtm;
    private final LocalDateTime updDtm;

    public Member(Member value) {
        this.mbrId = value.mbrId;
        this.mbrEmail = value.mbrEmail;
        this.mbrNckNm = value.mbrNckNm;
        this.mbrGndr = value.mbrGndr;
        this.mbrSclId = value.mbrSclId;
        this.mbrSclTyp = value.mbrSclTyp;
        this.mbrArgmYn = value.mbrArgmYn;
        this.mbrVldYn = value.mbrVldYn;
        this.creDtm = value.creDtm;
        this.updDtm = value.updDtm;
    }

    public Member(
        ULong mbrId,
        String mbrEmail,
        String mbrNckNm,
        String mbrGndr,
        String mbrSclId,
        String mbrSclTyp,
        String mbrArgmYn,
        String mbrVldYn,
        LocalDateTime creDtm,
        LocalDateTime updDtm
    ) {
        this.mbrId = mbrId;
        this.mbrEmail = mbrEmail;
        this.mbrNckNm = mbrNckNm;
        this.mbrGndr = mbrGndr;
        this.mbrSclId = mbrSclId;
        this.mbrSclTyp = mbrSclTyp;
        this.mbrArgmYn = mbrArgmYn;
        this.mbrVldYn = mbrVldYn;
        this.creDtm = creDtm;
        this.updDtm = updDtm;
    }

    /**
     * Getter for <code>spotfinder.MEMBER.MBR_ID</code>. 회원 ID
     */
    public ULong getMbrId() {
        return this.mbrId;
    }

    /**
     * Getter for <code>spotfinder.MEMBER.MBR_EMAIL</code>. 이메일
     */
    public String getMbrEmail() {
        return this.mbrEmail;
    }

    /**
     * Getter for <code>spotfinder.MEMBER.MBR_NCK_NM</code>. 닉네임
     */
    public String getMbrNckNm() {
        return this.mbrNckNm;
    }

    /**
     * Getter for <code>spotfinder.MEMBER.MBR_GNDR</code>. 성별
     */
    public String getMbrGndr() {
        return this.mbrGndr;
    }

    /**
     * Getter for <code>spotfinder.MEMBER.MBR_SCL_ID</code>. 소셜 ID
     */
    public String getMbrSclId() {
        return this.mbrSclId;
    }

    /**
     * Getter for <code>spotfinder.MEMBER.MBR_SCL_TYP</code>. 소셜 타입
     */
    public String getMbrSclTyp() {
        return this.mbrSclTyp;
    }

    /**
     * Getter for <code>spotfinder.MEMBER.MBR_ARGM_YN</code>. 약관 동의 여부
     */
    public String getMbrArgmYn() {
        return this.mbrArgmYn;
    }

    /**
     * Getter for <code>spotfinder.MEMBER.MBR_VLD_YN</code>. 유효여부
     */
    public String getMbrVldYn() {
        return this.mbrVldYn;
    }

    /**
     * Getter for <code>spotfinder.MEMBER.CRE_DTM</code>. 등록일시
     */
    public LocalDateTime getCreDtm() {
        return this.creDtm;
    }

    /**
     * Getter for <code>spotfinder.MEMBER.UPD_DTM</code>. 수정일시
     */
    public LocalDateTime getUpdDtm() {
        return this.updDtm;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Member other = (Member) obj;
        if (this.mbrId == null) {
            if (other.mbrId != null)
                return false;
        }
        else if (!this.mbrId.equals(other.mbrId))
            return false;
        if (this.mbrEmail == null) {
            if (other.mbrEmail != null)
                return false;
        }
        else if (!this.mbrEmail.equals(other.mbrEmail))
            return false;
        if (this.mbrNckNm == null) {
            if (other.mbrNckNm != null)
                return false;
        }
        else if (!this.mbrNckNm.equals(other.mbrNckNm))
            return false;
        if (this.mbrGndr == null) {
            if (other.mbrGndr != null)
                return false;
        }
        else if (!this.mbrGndr.equals(other.mbrGndr))
            return false;
        if (this.mbrSclId == null) {
            if (other.mbrSclId != null)
                return false;
        }
        else if (!this.mbrSclId.equals(other.mbrSclId))
            return false;
        if (this.mbrSclTyp == null) {
            if (other.mbrSclTyp != null)
                return false;
        }
        else if (!this.mbrSclTyp.equals(other.mbrSclTyp))
            return false;
        if (this.mbrArgmYn == null) {
            if (other.mbrArgmYn != null)
                return false;
        }
        else if (!this.mbrArgmYn.equals(other.mbrArgmYn))
            return false;
        if (this.mbrVldYn == null) {
            if (other.mbrVldYn != null)
                return false;
        }
        else if (!this.mbrVldYn.equals(other.mbrVldYn))
            return false;
        if (this.creDtm == null) {
            if (other.creDtm != null)
                return false;
        }
        else if (!this.creDtm.equals(other.creDtm))
            return false;
        if (this.updDtm == null) {
            if (other.updDtm != null)
                return false;
        }
        else if (!this.updDtm.equals(other.updDtm))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.mbrId == null) ? 0 : this.mbrId.hashCode());
        result = prime * result + ((this.mbrEmail == null) ? 0 : this.mbrEmail.hashCode());
        result = prime * result + ((this.mbrNckNm == null) ? 0 : this.mbrNckNm.hashCode());
        result = prime * result + ((this.mbrGndr == null) ? 0 : this.mbrGndr.hashCode());
        result = prime * result + ((this.mbrSclId == null) ? 0 : this.mbrSclId.hashCode());
        result = prime * result + ((this.mbrSclTyp == null) ? 0 : this.mbrSclTyp.hashCode());
        result = prime * result + ((this.mbrArgmYn == null) ? 0 : this.mbrArgmYn.hashCode());
        result = prime * result + ((this.mbrVldYn == null) ? 0 : this.mbrVldYn.hashCode());
        result = prime * result + ((this.creDtm == null) ? 0 : this.creDtm.hashCode());
        result = prime * result + ((this.updDtm == null) ? 0 : this.updDtm.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Member (");

        sb.append(mbrId);
        sb.append(", ").append(mbrEmail);
        sb.append(", ").append(mbrNckNm);
        sb.append(", ").append(mbrGndr);
        sb.append(", ").append(mbrSclId);
        sb.append(", ").append(mbrSclTyp);
        sb.append(", ").append(mbrArgmYn);
        sb.append(", ").append(mbrVldYn);
        sb.append(", ").append(creDtm);
        sb.append(", ").append(updDtm);

        sb.append(")");
        return sb.toString();
    }
}
