/*
 * This file is generated by jOOQ.
 */
package trash.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.ULong;


/**
 * 신고 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Report implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong rptSeq;
    private final String fcltyId;
    private final ULong mbrSeq;
    private final String rptCtt;
    private final String rptAns;
    private final LocalDateTime creDtm;
    private final LocalDateTime updDtm;

    public Report(Report value) {
        this.rptSeq = value.rptSeq;
        this.fcltyId = value.fcltyId;
        this.mbrSeq = value.mbrSeq;
        this.rptCtt = value.rptCtt;
        this.rptAns = value.rptAns;
        this.creDtm = value.creDtm;
        this.updDtm = value.updDtm;
    }

    public Report(
        ULong rptSeq,
        String fcltyId,
        ULong mbrSeq,
        String rptCtt,
        String rptAns,
        LocalDateTime creDtm,
        LocalDateTime updDtm
    ) {
        this.rptSeq = rptSeq;
        this.fcltyId = fcltyId;
        this.mbrSeq = mbrSeq;
        this.rptCtt = rptCtt;
        this.rptAns = rptAns;
        this.creDtm = creDtm;
        this.updDtm = updDtm;
    }

    /**
     * Getter for <code>spotfinder.REPORT.RPT_SEQ</code>. 신고 일련번호
     */
    public ULong getRptSeq() {
        return this.rptSeq;
    }

    /**
     * Getter for <code>spotfinder.REPORT.FCLTY_ID</code>. 시설물 ID
     */
    public String getFcltyId() {
        return this.fcltyId;
    }

    /**
     * Getter for <code>spotfinder.REPORT.MBR_SEQ</code>. 회원 일련번호
     */
    public ULong getMbrSeq() {
        return this.mbrSeq;
    }

    /**
     * Getter for <code>spotfinder.REPORT.RPT_CTT</code>. 신고 내용
     */
    public String getRptCtt() {
        return this.rptCtt;
    }

    /**
     * Getter for <code>spotfinder.REPORT.RPT_ANS</code>. 답변
     */
    public String getRptAns() {
        return this.rptAns;
    }

    /**
     * Getter for <code>spotfinder.REPORT.CRE_DTM</code>. 등록일시
     */
    public LocalDateTime getCreDtm() {
        return this.creDtm;
    }

    /**
     * Getter for <code>spotfinder.REPORT.UPD_DTM</code>. 수정일시
     */
    public LocalDateTime getUpdDtm() {
        return this.updDtm;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Report other = (Report) obj;
        if (this.rptSeq == null) {
            if (other.rptSeq != null)
                return false;
        }
        else if (!this.rptSeq.equals(other.rptSeq))
            return false;
        if (this.fcltyId == null) {
            if (other.fcltyId != null)
                return false;
        }
        else if (!this.fcltyId.equals(other.fcltyId))
            return false;
        if (this.mbrSeq == null) {
            if (other.mbrSeq != null)
                return false;
        }
        else if (!this.mbrSeq.equals(other.mbrSeq))
            return false;
        if (this.rptCtt == null) {
            if (other.rptCtt != null)
                return false;
        }
        else if (!this.rptCtt.equals(other.rptCtt))
            return false;
        if (this.rptAns == null) {
            if (other.rptAns != null)
                return false;
        }
        else if (!this.rptAns.equals(other.rptAns))
            return false;
        if (this.creDtm == null) {
            if (other.creDtm != null)
                return false;
        }
        else if (!this.creDtm.equals(other.creDtm))
            return false;
        if (this.updDtm == null) {
            if (other.updDtm != null)
                return false;
        }
        else if (!this.updDtm.equals(other.updDtm))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.rptSeq == null) ? 0 : this.rptSeq.hashCode());
        result = prime * result + ((this.fcltyId == null) ? 0 : this.fcltyId.hashCode());
        result = prime * result + ((this.mbrSeq == null) ? 0 : this.mbrSeq.hashCode());
        result = prime * result + ((this.rptCtt == null) ? 0 : this.rptCtt.hashCode());
        result = prime * result + ((this.rptAns == null) ? 0 : this.rptAns.hashCode());
        result = prime * result + ((this.creDtm == null) ? 0 : this.creDtm.hashCode());
        result = prime * result + ((this.updDtm == null) ? 0 : this.updDtm.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Report (");

        sb.append(rptSeq);
        sb.append(", ").append(fcltyId);
        sb.append(", ").append(mbrSeq);
        sb.append(", ").append(rptCtt);
        sb.append(", ").append(rptAns);
        sb.append(", ").append(creDtm);
        sb.append(", ").append(updDtm);

        sb.append(")");
        return sb.toString();
    }
}
