/*
 * This file is generated by jOOQ.
 */
package trash.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.ULong;


/**
 * 리뷰 테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Review implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong rvwId;
    private final String rvwCtt;
    private final ULong mbrId;
    private final ULong fcltyId;
    private final LocalDateTime creDtm;
    private final LocalDateTime updDtm;

    public Review(Review value) {
        this.rvwId = value.rvwId;
        this.rvwCtt = value.rvwCtt;
        this.mbrId = value.mbrId;
        this.fcltyId = value.fcltyId;
        this.creDtm = value.creDtm;
        this.updDtm = value.updDtm;
    }

    public Review(
        ULong rvwId,
        String rvwCtt,
        ULong mbrId,
        ULong fcltyId,
        LocalDateTime creDtm,
        LocalDateTime updDtm
    ) {
        this.rvwId = rvwId;
        this.rvwCtt = rvwCtt;
        this.mbrId = mbrId;
        this.fcltyId = fcltyId;
        this.creDtm = creDtm;
        this.updDtm = updDtm;
    }

    /**
     * Getter for <code>spotfinder.REVIEW.RVW_ID</code>. 리뷰 ID
     */
    public ULong getRvwId() {
        return this.rvwId;
    }

    /**
     * Getter for <code>spotfinder.REVIEW.RVW_CTT</code>. 리뷰 내용
     */
    public String getRvwCtt() {
        return this.rvwCtt;
    }

    /**
     * Getter for <code>spotfinder.REVIEW.MBR_ID</code>. 회원 ID
     */
    public ULong getMbrId() {
        return this.mbrId;
    }

    /**
     * Getter for <code>spotfinder.REVIEW.FCLTY_ID</code>. 시설물 ID
     */
    public ULong getFcltyId() {
        return this.fcltyId;
    }

    /**
     * Getter for <code>spotfinder.REVIEW.CRE_DTM</code>. 등록일시
     */
    public LocalDateTime getCreDtm() {
        return this.creDtm;
    }

    /**
     * Getter for <code>spotfinder.REVIEW.UPD_DTM</code>. 수정일시
     */
    public LocalDateTime getUpdDtm() {
        return this.updDtm;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Review other = (Review) obj;
        if (this.rvwId == null) {
            if (other.rvwId != null)
                return false;
        }
        else if (!this.rvwId.equals(other.rvwId))
            return false;
        if (this.rvwCtt == null) {
            if (other.rvwCtt != null)
                return false;
        }
        else if (!this.rvwCtt.equals(other.rvwCtt))
            return false;
        if (this.mbrId == null) {
            if (other.mbrId != null)
                return false;
        }
        else if (!this.mbrId.equals(other.mbrId))
            return false;
        if (this.fcltyId == null) {
            if (other.fcltyId != null)
                return false;
        }
        else if (!this.fcltyId.equals(other.fcltyId))
            return false;
        if (this.creDtm == null) {
            if (other.creDtm != null)
                return false;
        }
        else if (!this.creDtm.equals(other.creDtm))
            return false;
        if (this.updDtm == null) {
            if (other.updDtm != null)
                return false;
        }
        else if (!this.updDtm.equals(other.updDtm))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.rvwId == null) ? 0 : this.rvwId.hashCode());
        result = prime * result + ((this.rvwCtt == null) ? 0 : this.rvwCtt.hashCode());
        result = prime * result + ((this.mbrId == null) ? 0 : this.mbrId.hashCode());
        result = prime * result + ((this.fcltyId == null) ? 0 : this.fcltyId.hashCode());
        result = prime * result + ((this.creDtm == null) ? 0 : this.creDtm.hashCode());
        result = prime * result + ((this.updDtm == null) ? 0 : this.updDtm.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Review (");

        sb.append(rvwId);
        sb.append(", ").append(rvwCtt);
        sb.append(", ").append(mbrId);
        sb.append(", ").append(fcltyId);
        sb.append(", ").append(creDtm);
        sb.append(", ").append(updDtm);

        sb.append(")");
        return sb.toString();
    }
}
