spring:
  application:
    name: trash

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trash
    username: root
    password: 1234

  data:
    mongodb:
      uri: mongodb://localhost:27017/spot-finder

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
    database: mysql

  messages:
    basename: messages/validation
    encoding: UTF-8
    fallbackToSystemLocale: false
    alwaysUseMessageFormat: true

  config:
    import: application-secret.yml
