/*
 * This file is generated by jOOQ.
 */
package trash;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import trash.tables.Admin;
import trash.tables.Facility;
import trash.tables.FacilityApprovalHistory;
import trash.tables.FacilityImage;
import trash.tables.Member;
import trash.tables.Notice;
import trash.tables.Report;
import trash.tables.Review;
import trash.tables.Token;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Spotfinder extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>spotfinder</code>
     */
    public static final Spotfinder SPOTFINDER = new Spotfinder();

    /**
     * 관리자 테이블
     */
    public final Admin ADMIN = Admin.ADMIN;

    /**
     * 시설물 테이블
     */
    public final Facility FACILITY = Facility.FACILITY;

    /**
     * 시설물 승인 이력 테이블
     */
    public final FacilityApprovalHistory FACILITY_APPROVAL_HISTORY = FacilityApprovalHistory.FACILITY_APPROVAL_HISTORY;

    /**
     * 시설물 이미지 테이블
     */
    public final FacilityImage FACILITY_IMAGE = FacilityImage.FACILITY_IMAGE;

    /**
     * The table <code>spotfinder.MEMBER</code>.
     */
    public final Member MEMBER = Member.MEMBER;

    /**
     * The table <code>spotfinder.NOTICE</code>.
     */
    public final Notice NOTICE = Notice.NOTICE;

    /**
     * 신고 테이블
     */
    public final Report REPORT = Report.REPORT;

    /**
     * 리뷰 테이블
     */
    public final Review REVIEW = Review.REVIEW;

    /**
     * The table <code>spotfinder.TOKEN</code>.
     */
    public final Token TOKEN = Token.TOKEN;

    /**
     * No further instances allowed
     */
    private Spotfinder() {
        super("spotfinder", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Admin.ADMIN,
            Facility.FACILITY,
            FacilityApprovalHistory.FACILITY_APPROVAL_HISTORY,
            FacilityImage.FACILITY_IMAGE,
            Member.MEMBER,
            Notice.NOTICE,
            Report.REPORT,
            Review.REVIEW,
            Token.TOKEN
        );
    }
}
