/*
 * This file is generated by jOOQ.
 */
package trash;


import trash.tables.Member;


/**
 * Convenience access to all tables in trash.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>trash.MEMBER</code>.
     */
    public static final Member MEMBER = Member.MEMBER;
}
