/*
 * This file is generated by jOOQ.
 */
package trash;


import trash.tables.Admin;
import trash.tables.Member;
import trash.tables.Review;


/**
 * Convenience access to all tables in trash.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 관리자 테이블
     */
    public static final Admin ADMIN = Admin.ADMIN;

    /**
     * The table <code>trash.MEMBER</code>.
     */
    public static final Member MEMBER = Member.MEMBER;

    /**
     * 리뷰 테이블
     */
    public static final Review REVIEW = Review.REVIEW;
}
