/*
 * This file is generated by jOOQ.
 */
package trash;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import trash.tables.Admin;
import trash.tables.Member;
import trash.tables.Review;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Trash extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>trash</code>
     */
    public static final Trash TRASH = new Trash();

    /**
     * 관리자 테이블
     */
    public final Admin ADMIN = Admin.ADMIN;

    /**
     * The table <code>trash.MEMBER</code>.
     */
    public final Member MEMBER = Member.MEMBER;

    /**
     * 리뷰 테이블
     */
    public final Review REVIEW = Review.REVIEW;

    /**
     * No further instances allowed
     */
    private Trash() {
        super("trash", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Admin.ADMIN,
            Member.MEMBER,
            Review.REVIEW
        );
    }
}
