name: Java CI/CD with Gradle

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GIT_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push spotfinder-admin Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spotfinder-admin:latest -f trash-admin/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/spotfinder-admin:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ADMIN_EC2_HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }} # pem 키
          script: |
            docker stop spotfinder-admin || true

            docker rm spotfinder-admin || true

            docker pull ${{ secrets.DOCKER_USERNAME }}/spotfinder-admin:latest

            docker run -d --name spotfinder-admin -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/spotfinder-admin:latest
